scons `
    platform=web `
    target=editor `
    production=yes `
    lto=none `
    optimize=size `
    deprecated=false `
    disable_xr=true `
    disable_overrides=true `
    engine_update_check=false `
    cache_path=".scons" `
    cache_limit=10 `
    modules_enabled_by_default=false `
    module_freetype_enabled=true `
    module_regex_enabled=true `
    module_svg_enabled=true `
    module_text_server_adv_enabled=true `
    module_gdscript_enabled=true `
    module_ogg_enabled=true `
    module_vorbis_enabled=true `
    module_navigation2d_enabled=true
npx brotli-cli compress -q 5 --br=false bin\.web_zip\godot.editor.wasm 